//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36415
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace FWFrame.Mapper.MappingConfig {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.teradyne.com/FWTool/Mapping.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.teradyne.com/FWTool/Mapping.xsd", IsNullable=false)]
    public partial class Mappings {
        
        private Mapping[] mappingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Mapping")]
        public Mapping[] Mapping {
            get {
                return this.mappingField;
            }
            set {
                this.mappingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.teradyne.com/FWTool/Mapping.xsd")]
    public partial class Mapping {
        
        private string blockTypeField;
        
        private string commandField;
        
        private string[] generatorField;
        
        /// <remarks/>
        public string BlockType {
            get {
                return this.blockTypeField;
            }
            set {
                this.blockTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Command {
            get {
                return this.commandField;
            }
            set {
                this.commandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Generator")]
        public string[] Generator {
            get {
                return this.generatorField;
            }
            set {
                this.generatorField = value;
            }
        }
    }
}
