Attribute VB_Name = "AHB_REG_MAP7"
'T-AutoGen-Version : 1.3.0.1
'ProjectName_A1_TestPlan_20220226.xlsx
'ProjectName_A0_otp_AVA.otp
'ProjectName_A0_OTP_register_map.yaml
'ProjectName_A0_Pattern_List_Ext_20190823.csv
'ProjectName_A0_scgh_file#1_20200207.xlsx
'ProjectName_A0_VBTPOP_Gen_tool_MP10P_BuckSW_UVI80_DiffMeter_20200430.xlsm
'Public Enum RTC_SCRATCHPAD_SCRATCHPAD_SCRATCH_18
'Addr = &HD112&
'DATA = &H0
'End Enum
'Public Enum RTC_SCRATCHPAD_SCRATCHPAD_SCRATCH_19
'Addr = &HD113&
'DATA = &H0
'End Enum
'Public Enum RTC_FAULT_LOG_LOG_FAULT1
'Addr = &HD200&
'FLT_POR = &HFE
'FLT_RST = &HFD
'FLT_POR_VDDRTC = &HFB
'FLT_RST_VDDRTC = &HF7
'FLT_OVERTEMP = &HEF
'FLT_POR_WARN = &HDF
'FLT_VDDMAIN_UVLO = &HBF
'FLT_VDDMAIN_OVLO = &H7F
'End Enum
'Public Enum RTC_FAULT_LOG_LOG_FAULT2
'Addr = &HD201&
'FLT_TWO_FINGER_RST = &HFE
'FLT_CRASH_IN = &HFD
'FLT_BTN_SEQ_RESET = &HFB
'FLT_RESET_IN_1 = &HF7
'FLT_RESET_IN_2 = &HEF
'FLT_RESET_IN_3 = &HDF
'FLT_BTN_SHDN = &HBF
'FLT_VDD_BOOST_UVLO = &H7F
'End Enum
'Public Enum RTC_FAULT_LOG_LOG_FAULT3
'Addr = &HD202&
'FLT_SPMI_FAULT = &HFE
'FLT_NTC_SHDN = &HFD
'FLT_DBLCLICK_TIMEOUT = &HFB
'FLT_WALLET_CRASH_SEQ = &HF7
'FLT_VDDMAIN_UVLO_HOLD = &HEF
'FLT_WATCHDOG_TIMEOUT = &HDF
'FLT_BUTTON_DFU_RECOVER = &HBF
'FLT_SCRASH_IN = &H7F
'End Enum
'Public Enum RTC_FAULT_LOG_LOG_FAULT4
'Addr = &HD203&
'FLT_OTP_CRC = &HFE
'FLT_SGPIO = &HFD
'FLT_TEMP_ABS_BUCK0 = &HFB
'FLT_TEMP_ABS_BUCK1 = &HF7
'FLT_BSTLQ_UVLO = &HEF
'End Enum
'Public Enum RTC_LDO_LDO_RTC_CNTRL_0
'Addr = &HD300&
'ALWAYS_RTC_LDO = &HFE
'FORCE_OFF = &HFD
'POR_SET = &H8F
'End Enum
'Public Enum RTC_LDO_LDO_RTC_CNTRL_1
'Addr = &HD301&
'INTERNAL_COMP = &HFE
'SPARE = &HF9
'End Enum
'Public Enum RTC_LDO_LDO_RTC_TRIM_0
'Addr = &HD302&
'BG_TRIM = &HF0
'TM_BLOCK_BGOK = &HEF
'TM_FORCE_REF = &HDF
'End Enum
'Public Enum RTC_LDO_LDO_RTC_ATE_0
'Addr = &HD303&
'TEST_FORCE_ALT = &HFE
'End Enum
'Public Enum RTC_LDO_PD_RTC_XTAL_TRIM
'Addr = &HD380&
'CSR = &HFC
'ENABLE = &HFB
'CSR_BACKUP = &HCF
'CSR_BACKUP_MODE = &H3F
'End Enum
'Public Enum RTC_LDO_PD_RTC_TEST_RST
'Addr = &HD381&
'REQUEST_RST = &HFE
'REQUEST_POR = &HFD
'End Enum
'Public Enum RTC_LDO_PD_RTC_TEST_ISO
'Addr = &HD383&
'MASK_ISO = &HFE
'MASK_ISO_KEEP = &HFD
'MASK_ISO_SLAVE_TERM_ACK = &HFB
'ISOLATE = &HF7
'End Enum
'Public Enum RTC_LDO_PD_RTC_POR_WARN
'Addr = &HD384&
'EN = &HFE
'BLANK = &HF1
'VDDRTC_SELECT = &HCF
'End Enum
